/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.lang.reflect.Proxy;

public class App {

    public static void main(String[] args) {
        Man mohan = new Man("mohan",20,"patna","india");

        ClassLoader mohanClassLoader = mohan.getClass().getClassLoader();

        Class[] interfaces = mohan.getClass().getInterfaces();

        Person proxyMohan = (Person)
                Proxy.newProxyInstance(mohanClassLoader,interfaces,new PersonInvocationHandler(mohan));

        proxyMohan.introduce(mohan.getName());
    }
}
